--CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE bdi221;
GO

-- DEFINIR QUAL BANCO DE DADOS VAMOS UTILIZAR
USE bdi221;
GO

-- CRIAÇÃO DA TABELA PRODUTO
CREATE TABLE PRODUTOS(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(255),
	VALOR DECIMAL(5,2)
);
GO
-- ADICIONAR O CAMPO TIPO
ALTER TABLE PRODUTOS
ADD TIPO CHAR(1) NULL;
GO

SELECT * FROM PRODUTOS

-- ADICIONAR CHAVE PRIMARIA
ALTER TABLE produtos
ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID);
GO

-- CRIAÇÃO DA TABELA PRONTUARIO
CREATE TABLE PRONTUARIO(
    ID INT IDENTITY(1,1)NOT NULL,
    DESCRICAO VARCHAR (255),
    TEMPERATURA DECIMAL(3,1),
    PESO DECIMAL(5,2)
);
GO
ALTER TABLE PRONTUARIO ADD CONSTRAINT PK_PRONTUARIO PRIMARY KEY(ID);

-- CRIAÇÃO DA TABELA PET
CREATE TABLE PET(
    ID INT IDENTITY(1,1)NOT NULL,
    NOME VARCHAR(50),
    ESPECIE VARCHAR(50),
    PORTE VARCHAR(50),
    -- DATA_NASC DATE ()
);
GO

ALTER TABLE PET ADD CONSTRAINT FK_PRONTUARIO FOREIGN KEY(ID) REFERENCES PRONTUARIO(ID);
GO

